requires 'FCGI';
requires 'FCGI::ProcManager';
requires 'Email::Stuffer';
requires 'JSON';
requires 'List::Util' => '1.33';
requires 'DBD::mysql' => '4.025';
requires 'DBIx::Class' => '0.08250';
requires 'HTML::TreeBuilder';
requires 'HTML::Element';
requires 'HTTP::AcceptLanguage';
requires 'MooseX::NonMoose';
requires 'Catalyst::Runtime', '5.90093';
requires 'Catalyst::View::TT';
requires 'Catalyst::Action::REST';
requires 'Catalyst::Authentication::Store::DBIx::Class';
requires 'Catalyst::Plugin::Authentication';
requires 'Catalyst::Plugin::Session::Store::FastMmap';
requires 'Catalyst::Plugin::Session::State::Cookie';
requires 'Catalyst::Plugin::ConfigLoader';
requires 'Catalyst::Plugin::Static::Simple';
requires 'Catalyst::Action::RenderView';
requires 'Catalyst::Restarter';
requires 'Moose';
requires 'namespace::autoclean';
requires 'Config::General';
requires 'Text::Markdown';
